// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9Zy05JHOby_mRHd29NCqRwrdEe5jlp8',
    appId: '1:627408638546:web:8bf3f428f2d9f10ab8c58b',
    messagingSenderId: '627408638546',
    projectId: 'jackson-uts-e1822',
    authDomain: 'jackson-uts-e1822.firebaseapp.com',
    storageBucket: 'jackson-uts-e1822.firebasestorage.app',
    measurementId: 'G-X25309WBSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDN6c2HO9FZQUSiwu9jG-dD6xys_GevA',
    appId: '1:627408638546:android:24c65da642ce8c9cb8c58b',
    messagingSenderId: '627408638546',
    projectId: 'jackson-uts-e1822',
    storageBucket: 'jackson-uts-e1822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIZhnnbuR1K6TV8rSkjDMTSeW6tbkJR1c',
    appId: '1:627408638546:ios:127208f8854a9a60b8c58b',
    messagingSenderId: '627408638546',
    projectId: 'jackson-uts-e1822',
    storageBucket: 'jackson-uts-e1822.firebasestorage.app',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIZhnnbuR1K6TV8rSkjDMTSeW6tbkJR1c',
    appId: '1:627408638546:ios:127208f8854a9a60b8c58b',
    messagingSenderId: '627408638546',
    projectId: 'jackson-uts-e1822',
    storageBucket: 'jackson-uts-e1822.firebasestorage.app',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9Zy05JHOby_mRHd29NCqRwrdEe5jlp8',
    appId: '1:627408638546:web:c628c8fe22c885f3b8c58b',
    messagingSenderId: '627408638546',
    projectId: 'jackson-uts-e1822',
    authDomain: 'jackson-uts-e1822.firebaseapp.com',
    storageBucket: 'jackson-uts-e1822.firebasestorage.app',
    measurementId: 'G-2XJDTCYWZQ',
  );
}
